
Skip to content

    Andre-Cardozo-Web
    SNESticleAurora-1080P-GSM

Repository navigation

    Code
    Pull requests
    Actions
    Projects
    Wiki
    Security and quality
    Insights
    Settings

Continuous Release
Update continuous.yml #246

    All jobs
    Run details

Annotations
1 error and 1 warning
build
failed in 1 minute in 1m 6s
0s
11s
5s
43s
0s
0s
0s
2s
0s
0s
1s
      |            ^~~~~~~~~~~~~
src/platform/ps2/system/mainloop_state.cpp:65:27: error: 'nOriginalMax' was not declared in this scope
   65 |     if (nMaxChars <= 0 && nOriginalMax >= 3) { sprintf(pOut - 3, "%03u", (unsigned int)(hash % 1000)); }
      |                           ^~~~~~~~~~~~
src/platform/ps2/system/mainloop_state.cpp: In function 'Bool _MainLoopSramUsbReady()':
src/platform/ps2/system/mainloop_state.cpp:81:17: warning: unused variable 'Status' [-Wunused-variable]
   81 |     struct stat Status;
      |                 ^~~~~~
src/platform/ps2/system/mainloop_state.cpp: At global scope:
src/platform/ps2/system/mainloop_state.cpp:80:13: warning: 'Bool _MainLoopSramUsbReady()' defined but not used [-Wunused-function]
   80 | static Bool _MainLoopSramUsbReady() {
      |             ^~~~~~~~~~~~~~~~~~~~~
src/platform/ps2/system/mainloop_state.cpp:77:20: warning: 'const Char* _MainLoopSramRoot(MainLoopSramDeviceE)' defined but not used [-Wunused-function]
   77 | static const Char *_MainLoopSramRoot(MainLoopSramDeviceE eDevice) {
      |                    ^~~~~~~~~~~~~~~~~
src/platform/ps2/system/mainloop_state.cpp:71:20: warning: 'const Char* _MainLoopSramGetSystemDirectoryName()' defined but not used [-Wunused-function]
   71 | static const Char *_MainLoopSramGetSystemDirectoryName() {
      |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/platform/ps2/system/mainloop_state.cpp:41:29: warning: '_MainLoop_SramDevice' defined but not used [-Wunused-variable]
   41 | static MainLoopSramDeviceE  _MainLoop_SramDevice  = MAINLOOP_SRAMDEVICE_AUTO;
      |                             ^~~~~~~~~~~~~~~~~~~~
src/platform/ps2/system/mainloop_state.cpp:40:29: warning: '_MainLoop_StateDevice' defined but not used [-Wunused-variable]
   40 | static MainLoopStateDeviceE _MainLoop_StateDevice = MAINLOOP_STATEDEVICE_AUTO;
      |                             ^~~~~~~~~~~~~~~~~~~~~
make: *** [Makefile:62: build/obj/platform/ps2/system/mainloop_state.o] Error 1
Error: Process completed with exit code 2.
0s
0s
0s
1s
0s
0s
